#include "unistd.h"
#include "stdio.h"
#include "../../minilibx_opengl_20191021/mlx.h"
#include "fcntl.h"
#include "stdlib.h"
#include "string.h"
#include "stdbool.h"
#include "stdint.h"
#include "math.h"
#include "sys/time.h"

